### ISSUE TITLE
训练一段时间后，CE loss变为NAN

### ISSUE THREAD

**Issue by 834799106** [bubbliiiing/unet-pytorch#19]
您好，看了您的教程我试着自己搭建了一个U-Net模型，并采用Dice + CE loss作为损失函数，但在迭代几十个epoch后，我的CE loss返回了NAN值，反馈的结果是 ‘Function 'LogSoftmaxBackward' returned nan values in its 0th output.’ 同样的数据在您源码上运行没有出现这个问题，请问您是否知道些解决方法？

**Comment by bubbliiiing** [comment]
emm……啥意思呀你自己搭建的是错的吗0 0
