### ISSUE TITLE
裁剪预测图

### ISSUE THREAD

**Issue by WangRongsheng** [bubbliiiing/unet-pytorch#21]
你好，请问有没有crop检测结果的代码在里面或者大概怎么实现？
比如，我想用模型把舌头裁剪出：
![](https://s3.bmp.ovh/imgs/2022/03/84387da9ebbfb5b9.jpg)

**Comment by WangRongsheng** [comment]
我修改了参数：
![](https://s3.bmp.ovh/imgs/2022/03/04f15ff7a09480ad.jpg)
但是扣去了我需要的部分：
![](https://b2.kuibu.net/file/imgdisk/imgs/2022/03/d95b5c43545740bb.jpg)

请问我可以怎么修改？

**Comment by WangRongsheng** [comment]
已解决!
修改：
```python
# unet.py的第180行
seg_img = (np.expand_dims(pr != 0, -1) * np.array(old_img, np.float32)).astype('uint8')
为
seg_img = (np.expand_dims(pr != 1, -1) * np.array(old_img, np.float32)).astype('uint8')
```

**Comment by bubbliiiing** [comment]
……………………………………………………你这个图……晚上把我吓死 …………………………………………………………………………………………
