### ISSUE TITLE
Loss

### ISSUE THREAD

**Issue by SanQi888** [bubbliiiing/unet-pytorch#24]
不使用预训练模型，用ECSSD重新训练主干网络，数据集中有1000张图片，但每次epoch有450张，并且损失一直为0，期待您的回复

**Comment by bubbliiiing** [comment]
为0是因为格式错了的

**Comment by bubbliiiing** [comment]
为0是因为格式错了的

**Comment by SanQi888** [comment]
标签只能用专用的语义分割数据集吗？使用二值标签可以吗（ECSSD DUTS-TE等等）

**Comment by bubbliiiing** [comment]
二值标签需要简单的更改
255=>1即可
