### ISSUE TITLE
what's "nbs" mean?

### ISSUE THREAD

**Issue by kywish** [bubbliiiing/unet-pytorch#70]
[这段](https://github.com/bubbliiiing/unet-pytorch/blob/b3ed98897d823465eae30bd41894b305303ef965/train.py#L384) 调整学习率的地方没看懂：
                #-------------------------------------------------------------------#
                #   判断当前batch_size，自适应调整学习率
                #-------------------------------------------------------------------#
                nbs             = 16
                lr_limit_max    = 1e-4 if optimizer_type == 'adam' else 1e-1
                lr_limit_min    = 1e-4 if optimizer_type == 'adam' else 5e-4
                Init_lr_fit     = min(max(batch_size / nbs * Init_lr, lr_limit_min), lr_limit_max)
                Min_lr_fit      = min(max(batch_size / nbs * Min_lr, lr_limit_min * 1e-2), lr_limit_max * 1e-2)

nbs是啥意思吗，为啥要batch_size除以nbs再×初始学习率？

**Comment by bubbliiiing** [comment]
一个学习率调节的方式，nbs只是个预先设定好的值
