### ISSUE TITLE
predict.py 报错

### ISSUE THREAD

**Issue by Unusual6** [bubbliiiing/unet-pytorch#71]
![image](https://github.com/bubbliiiing/unet-pytorch/assets/114602129/73a9feb8-2d19-4b6f-bf4a-21864bd127e1)
ni'h你好博主，跟着博客和视频做的，还是报错了。是因为我是远程linux服务器执行后没法显示图片的原因吗

**Comment by bubbliiiing** [comment]
服务器没法可视化

**Comment by Unusual6** [comment]
好的谢谢
